export interface Airport {
  iata: string;
  name: string;
  city: string;
  country: string;
}

export const airports: Airport[] = [
  // ── UAE ──
  { iata: "DXB", name: "Dubai International Airport", city: "Dubai", country: "UAE" },
  { iata: "DWC", name: "Al Maktoum International Airport", city: "Dubai", country: "UAE" },
  { iata: "AUH", name: "Abu Dhabi International Airport", city: "Abu Dhabi", country: "UAE" },
  { iata: "SHJ", name: "Sharjah International Airport", city: "Sharjah", country: "UAE" },
  { iata: "RKT", name: "Ras Al Khaimah International Airport", city: "Ras Al Khaimah", country: "UAE" },
  { iata: "FJR", name: "Fujairah International Airport", city: "Fujairah", country: "UAE" },

  // ── GCC ──
  { iata: "RUH", name: "King Khalid International Airport", city: "Riyadh", country: "Saudi Arabia" },
  { iata: "JED", name: "King Abdulaziz International Airport", city: "Jeddah", country: "Saudi Arabia" },
  { iata: "DMM", name: "King Fahd International Airport", city: "Dammam", country: "Saudi Arabia" },
  { iata: "MED", name: "Prince Mohammad Bin Abdulaziz Airport", city: "Madinah", country: "Saudi Arabia" },
  { iata: "TIF", name: "Taif Regional Airport", city: "Taif", country: "Saudi Arabia" },
  { iata: "ABT", name: "Al-Aqiq Airport", city: "Al Baha", country: "Saudi Arabia" },
  { iata: "KWI", name: "Kuwait International Airport", city: "Kuwait City", country: "Kuwait" },
  { iata: "BAH", name: "Bahrain International Airport", city: "Manama", country: "Bahrain" },
  { iata: "DOH", name: "Hamad International Airport", city: "Doha", country: "Qatar" },
  { iata: "MCT", name: "Muscat International Airport", city: "Muscat", country: "Oman" },
  { iata: "SLL", name: "Salalah Airport", city: "Salalah", country: "Oman" },

  // ── South Asia ──
  { iata: "KHI", name: "Jinnah International Airport", city: "Karachi", country: "Pakistan" },
  { iata: "LHE", name: "Allama Iqbal International Airport", city: "Lahore", country: "Pakistan" },
  { iata: "ISB", name: "Islamabad International Airport", city: "Islamabad", country: "Pakistan" },
  { iata: "PEW", name: "Bacha Khan International Airport", city: "Peshawar", country: "Pakistan" },
  { iata: "SKT", name: "Sialkot International Airport", city: "Sialkot", country: "Pakistan" },
  { iata: "MUX", name: "Multan International Airport", city: "Multan", country: "Pakistan" },
  { iata: "BHV", name: "Bahawalpur Airport", city: "Bahawalpur", country: "Pakistan" },
  { iata: "DEL", name: "Indira Gandhi International Airport", city: "New Delhi", country: "India" },
  { iata: "BOM", name: "Chhatrapati Shivaji Maharaj International Airport", city: "Mumbai", country: "India" },
  { iata: "MAA", name: "Chennai International Airport", city: "Chennai", country: "India" },
  { iata: "CCU", name: "Netaji Subhas Chandra Bose International Airport", city: "Kolkata", country: "India" },
  { iata: "BLR", name: "Kempegowda International Airport", city: "Bengaluru", country: "India" },
  { iata: "HYD", name: "Rajiv Gandhi International Airport", city: "Hyderabad", country: "India" },
  { iata: "COK", name: "Cochin International Airport", city: "Kochi", country: "India" },
  { iata: "TRV", name: "Trivandrum International Airport", city: "Thiruvananthapuram", country: "India" },
  { iata: "AMD", name: "Sardar Vallabhbhai Patel International Airport", city: "Ahmedabad", country: "India" },
  { iata: "PNQ", name: "Pune Airport", city: "Pune", country: "India" },
  { iata: "IXB", name: "Bagdogra Airport", city: "Siliguri", country: "India" },
  { iata: "CCJ", name: "Calicut International Airport", city: "Kozhikode", country: "India" },
  { iata: "DAC", name: "Hazrat Shahjalal International Airport", city: "Dhaka", country: "Bangladesh" },
  { iata: "CGP", name: "Shah Amanat International Airport", city: "Chittagong", country: "Bangladesh" },
  { iata: "CMB", name: "Bandaranaike International Airport", city: "Colombo", country: "Sri Lanka" },
  { iata: "KTM", name: "Tribhuvan International Airport", city: "Kathmandu", country: "Nepal" },
  { iata: "MLE", name: "Velana International Airport", city: "Malé", country: "Maldives" },

  // ── Southeast Asia ──
  { iata: "SIN", name: "Changi Airport", city: "Singapore", country: "Singapore" },
  { iata: "KUL", name: "Kuala Lumpur International Airport", city: "Kuala Lumpur", country: "Malaysia" },
  { iata: "PEN", name: "Penang International Airport", city: "Penang", country: "Malaysia" },
  { iata: "BKK", name: "Suvarnabhumi Airport", city: "Bangkok", country: "Thailand" },
  { iata: "DMK", name: "Don Mueang International Airport", city: "Bangkok", country: "Thailand" },
  { iata: "HKT", name: "Phuket International Airport", city: "Phuket", country: "Thailand" },
  { iata: "CNX", name: "Chiang Mai International Airport", city: "Chiang Mai", country: "Thailand" },
  { iata: "CGK", name: "Soekarno-Hatta International Airport", city: "Jakarta", country: "Indonesia" },
  { iata: "DPS", name: "Ngurah Rai International Airport", city: "Denpasar (Bali)", country: "Indonesia" },
  { iata: "SUB", name: "Juanda International Airport", city: "Surabaya", country: "Indonesia" },
  { iata: "MNL", name: "Ninoy Aquino International Airport", city: "Manila", country: "Philippines" },
  { iata: "CEB", name: "Mactan-Cebu International Airport", city: "Cebu", country: "Philippines" },
  { iata: "SGN", name: "Tan Son Nhat International Airport", city: "Ho Chi Minh City", country: "Vietnam" },
  { iata: "HAN", name: "Noi Bai International Airport", city: "Hanoi", country: "Vietnam" },
  { iata: "DAD", name: "Da Nang International Airport", city: "Da Nang", country: "Vietnam" },
  { iata: "REP", name: "Siem Reap International Airport", city: "Siem Reap", country: "Cambodia" },
  { iata: "PNH", name: "Phnom Penh International Airport", city: "Phnom Penh", country: "Cambodia" },
  { iata: "RGN", name: "Yangon International Airport", city: "Yangon", country: "Myanmar" },

  // ── East Asia ──
  { iata: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "Hong Kong" },
  { iata: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China" },
  { iata: "SHA", name: "Shanghai Hongqiao International Airport", city: "Shanghai", country: "China" },
  { iata: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China" },
  { iata: "PKX", name: "Beijing Daxing International Airport", city: "Beijing", country: "China" },
  { iata: "CAN", name: "Guangzhou Baiyun International Airport", city: "Guangzhou", country: "China" },
  { iata: "CTU", name: "Chengdu Tianfu International Airport", city: "Chengdu", country: "China" },
  { iata: "SZX", name: "Shenzhen Bao'an International Airport", city: "Shenzhen", country: "China" },
  { iata: "XIY", name: "Xi'an Xianyang International Airport", city: "Xi'an", country: "China" },
  { iata: "CKG", name: "Chongqing Jiangbei International Airport", city: "Chongqing", country: "China" },
  { iata: "HGH", name: "Hangzhou Xiaoshan International Airport", city: "Hangzhou", country: "China" },
  { iata: "NKG", name: "Nanjing Lukou International Airport", city: "Nanjing", country: "China" },
  { iata: "KMG", name: "Kunming Changshui International Airport", city: "Kunming", country: "China" },
  { iata: "WUH", name: "Wuhan Tianhe International Airport", city: "Wuhan", country: "China" },
  { iata: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan" },
  { iata: "HND", name: "Haneda Airport", city: "Tokyo", country: "Japan" },
  { iata: "KIX", name: "Kansai International Airport", city: "Osaka", country: "Japan" },
  { iata: "NGO", name: "Chubu Centrair International Airport", city: "Nagoya", country: "Japan" },
  { iata: "CTS", name: "New Chitose Airport", city: "Sapporo", country: "Japan" },
  { iata: "FUK", name: "Fukuoka Airport", city: "Fukuoka", country: "Japan" },
  { iata: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea" },
  { iata: "GMP", name: "Gimpo International Airport", city: "Seoul", country: "South Korea" },
  { iata: "PUS", name: "Gimhae International Airport", city: "Busan", country: "South Korea" },
  { iata: "TPE", name: "Taiwan Taoyuan International Airport", city: "Taipei", country: "Taiwan" },

  // ── Central Asia & Caucasus ──
  { iata: "TBS", name: "Tbilisi International Airport", city: "Tbilisi", country: "Georgia" },
  { iata: "BUS", name: "Batumi International Airport", city: "Batumi", country: "Georgia" },
  { iata: "GYD", name: "Heydar Aliyev International Airport", city: "Baku", country: "Azerbaijan" },
  { iata: "EVN", name: "Zvartnots International Airport", city: "Yerevan", country: "Armenia" },
  { iata: "ALA", name: "Almaty International Airport", city: "Almaty", country: "Kazakhstan" },
  { iata: "NQZ", name: "Nursultan Nazarbayev International Airport", city: "Nur-Sultan", country: "Kazakhstan" },
  { iata: "TAS", name: "Tashkent International Airport", city: "Tashkent", country: "Uzbekistan" },
  { iata: "SVO", name: "Sheremetyevo International Airport", city: "Moscow", country: "Russia" },
  { iata: "DME", name: "Domodedovo International Airport", city: "Moscow", country: "Russia" },
  { iata: "LED", name: "Pulkovo Airport", city: "St. Petersburg", country: "Russia" },

  // ── Middle East / Levant ──
  { iata: "CAI", name: "Cairo International Airport", city: "Cairo", country: "Egypt" },
  { iata: "HRG", name: "Hurghada International Airport", city: "Hurghada", country: "Egypt" },
  { iata: "SSH", name: "Sharm el-Sheikh International Airport", city: "Sharm el-Sheikh", country: "Egypt" },
  { iata: "AMM", name: "Queen Alia International Airport", city: "Amman", country: "Jordan" },
  { iata: "BEY", name: "Beirut Rafic Hariri International Airport", city: "Beirut", country: "Lebanon" },
  { iata: "BGW", name: "Baghdad International Airport", city: "Baghdad", country: "Iraq" },
  { iata: "BSR", name: "Basra International Airport", city: "Basra", country: "Iraq" },
  { iata: "IKA", name: "Imam Khomeini International Airport", city: "Tehran", country: "Iran" },
  { iata: "MHD", name: "Mashhad International Airport", city: "Mashhad", country: "Iran" },
  { iata: "KBL", name: "Kabul International Airport", city: "Kabul", country: "Afghanistan" },
  { iata: "TLV", name: "Ben Gurion International Airport", city: "Tel Aviv", country: "Israel" },
  { iata: "DAM", name: "Damascus International Airport", city: "Damascus", country: "Syria" },
  { iata: "SAH", name: "Sana'a International Airport", city: "Sana'a", country: "Yemen" },

  // ── Africa ──
  { iata: "NBO", name: "Jomo Kenyatta International Airport", city: "Nairobi", country: "Kenya" },
  { iata: "MBA", name: "Mombasa Moi International Airport", city: "Mombasa", country: "Kenya" },
  { iata: "ADD", name: "Bole International Airport", city: "Addis Ababa", country: "Ethiopia" },
  { iata: "DAR", name: "Julius Nyerere International Airport", city: "Dar es Salaam", country: "Tanzania" },
  { iata: "KGL", name: "Kigali International Airport", city: "Kigali", country: "Rwanda" },
  { iata: "EBB", name: "Entebbe International Airport", city: "Kampala", country: "Uganda" },
  { iata: "LOS", name: "Murtala Muhammed International Airport", city: "Lagos", country: "Nigeria" },
  { iata: "ABV", name: "Nnamdi Azikiwe International Airport", city: "Abuja", country: "Nigeria" },
  { iata: "ACC", name: "Kotoka International Airport", city: "Accra", country: "Ghana" },
  { iata: "JNB", name: "O.R. Tambo International Airport", city: "Johannesburg", country: "South Africa" },
  { iata: "CPT", name: "Cape Town International Airport", city: "Cape Town", country: "South Africa" },
  { iata: "DUR", name: "King Shaka International Airport", city: "Durban", country: "South Africa" },
  { iata: "CMN", name: "Mohammed V International Airport", city: "Casablanca", country: "Morocco" },
  { iata: "RAK", name: "Marrakesh Menara Airport", city: "Marrakesh", country: "Morocco" },
  { iata: "TUN", name: "Tunis-Carthage International Airport", city: "Tunis", country: "Tunisia" },
  { iata: "ALG", name: "Houari Boumediene Airport", city: "Algiers", country: "Algeria" },
  { iata: "KRT", name: "Khartoum International Airport", city: "Khartoum", country: "Sudan" },
  { iata: "MGQ", name: "Aden Adde International Airport", city: "Mogadishu", country: "Somalia" },

  // ── Europe ──
  { iata: "LHR", name: "Heathrow Airport", city: "London", country: "United Kingdom" },
  { iata: "LGW", name: "Gatwick Airport", city: "London", country: "United Kingdom" },
  { iata: "STN", name: "Stansted Airport", city: "London", country: "United Kingdom" },
  { iata: "LTN", name: "Luton Airport", city: "London", country: "United Kingdom" },
  { iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom" },
  { iata: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom" },
  { iata: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom" },
  { iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom" },
  { iata: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France" },
  { iata: "ORY", name: "Orly Airport", city: "Paris", country: "France" },
  { iata: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "France" },
  { iata: "MRS", name: "Marseille Provence Airport", city: "Marseille", country: "France" },
  { iata: "LYS", name: "Lyon-Saint Exupéry Airport", city: "Lyon", country: "France" },
  { iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany" },
  { iata: "MUC", name: "Munich Airport", city: "Munich", country: "Germany" },
  { iata: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany" },
  { iata: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany" },
  { iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany" },
  { iata: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany" },
  { iata: "AMS", name: "Amsterdam Schiphol Airport", city: "Amsterdam", country: "Netherlands" },
  { iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium" },
  { iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland" },
  { iata: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland" },
  { iata: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria" },
  { iata: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", city: "Rome", country: "Italy" },
  { iata: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "Italy" },
  { iata: "LIN", name: "Milan Linate Airport", city: "Milan", country: "Italy" },
  { iata: "NAP", name: "Naples International Airport", city: "Naples", country: "Italy" },
  { iata: "VCE", name: "Venice Marco Polo Airport", city: "Venice", country: "Italy" },
  { iata: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport", city: "Madrid", country: "Spain" },
  { iata: "BCN", name: "Barcelona–El Prat Airport", city: "Barcelona", country: "Spain" },
  { iata: "AGP", name: "Málaga–Costa del Sol Airport", city: "Málaga", country: "Spain" },
  { iata: "PMI", name: "Palma de Mallorca Airport", city: "Palma", country: "Spain" },
  { iata: "LIS", name: "Lisbon Humberto Delgado Airport", city: "Lisbon", country: "Portugal" },
  { iata: "OPO", name: "Porto Airport", city: "Porto", country: "Portugal" },
  { iata: "ATH", name: "Athens International Airport", city: "Athens", country: "Greece" },
  { iata: "HER", name: "Heraklion International Airport", city: "Heraklion", country: "Greece" },
  { iata: "SKG", name: "Thessaloniki Airport", city: "Thessaloniki", country: "Greece" },
  { iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey" },
  { iata: "SAW", name: "Sabiha Gökçen International Airport", city: "Istanbul", country: "Turkey" },
  { iata: "AYT", name: "Antalya Airport", city: "Antalya", country: "Turkey" },
  { iata: "ESB", name: "Ankara Esenboğa International Airport", city: "Ankara", country: "Turkey" },
  { iata: "ADB", name: "Izmir Adnan Menderes Airport", city: "Izmir", country: "Turkey" },
  { iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland" },
  { iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic" },
  { iata: "BUD", name: "Budapest Ferenc Liszt International Airport", city: "Budapest", country: "Hungary" },
  { iata: "OTP", name: "Henri Coandă International Airport", city: "Bucharest", country: "Romania" },
  { iata: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria" },
  { iata: "BEG", name: "Belgrade Nikola Tesla Airport", city: "Belgrade", country: "Serbia" },
  { iata: "LJU", name: "Ljubljana Jože Pučnik Airport", city: "Ljubljana", country: "Slovenia" },
  { iata: "ZAG", name: "Zagreb Airport", city: "Zagreb", country: "Croatia" },
  { iata: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "Croatia" },
  { iata: "SPU", name: "Split Airport", city: "Split", country: "Croatia" },
  { iata: "SKP", name: "Skopje International Airport", city: "Skopje", country: "North Macedonia" },
  { iata: "TIA", name: "Tirana International Airport", city: "Tirana", country: "Albania" },
  { iata: "CPH", name: "Copenhagen Airport", city: "Copenhagen", country: "Denmark" },
  { iata: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo", country: "Norway" },
  { iata: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden" },
  { iata: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", country: "Finland" },
  { iata: "RIX", name: "Riga International Airport", city: "Riga", country: "Latvia" },
  { iata: "TLL", name: "Tallinn Airport", city: "Tallinn", country: "Estonia" },
  { iata: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "Lithuania" },
  { iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland" },
  { iata: "KEF", name: "Keflavík International Airport", city: "Reykjavík", country: "Iceland" },

  // ── North America ──
  { iata: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "USA" },
  { iata: "EWR", name: "Newark Liberty International Airport", city: "New York", country: "USA" },
  { iata: "LGA", name: "LaGuardia Airport", city: "New York", country: "USA" },
  { iata: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "USA" },
  { iata: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "USA" },
  { iata: "MDW", name: "Chicago Midway International Airport", city: "Chicago", country: "USA" },
  { iata: "ATL", name: "Hartsfield-Jackson Atlanta International Airport", city: "Atlanta", country: "USA" },
  { iata: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "USA" },
  { iata: "MIA", name: "Miami International Airport", city: "Miami", country: "USA" },
  { iata: "FLL", name: "Fort Lauderdale-Hollywood International Airport", city: "Fort Lauderdale", country: "USA" },
  { iata: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "USA" },
  { iata: "SEA", name: "Seattle-Tacoma International Airport", city: "Seattle", country: "USA" },
  { iata: "BOS", name: "Boston Logan International Airport", city: "Boston", country: "USA" },
  { iata: "IAD", name: "Washington Dulles International Airport", city: "Washington DC", country: "USA" },
  { iata: "DCA", name: "Ronald Reagan Washington National Airport", city: "Washington DC", country: "USA" },
  { iata: "IAH", name: "George Bush Intercontinental Airport", city: "Houston", country: "USA" },
  { iata: "HOU", name: "William P. Hobby Airport", city: "Houston", country: "USA" },
  { iata: "PHX", name: "Phoenix Sky Harbor International Airport", city: "Phoenix", country: "USA" },
  { iata: "LAS", name: "Harry Reid International Airport", city: "Las Vegas", country: "USA" },
  { iata: "MCO", name: "Orlando International Airport", city: "Orlando", country: "USA" },
  { iata: "TPA", name: "Tampa International Airport", city: "Tampa", country: "USA" },
  { iata: "DTW", name: "Detroit Metropolitan Airport", city: "Detroit", country: "USA" },
  { iata: "MSP", name: "Minneapolis-Saint Paul International Airport", city: "Minneapolis", country: "USA" },
  { iata: "DEN", name: "Denver International Airport", city: "Denver", country: "USA" },
  { iata: "PDX", name: "Portland International Airport", city: "Portland", country: "USA" },
  { iata: "SAN", name: "San Diego International Airport", city: "San Diego", country: "USA" },
  { iata: "SLC", name: "Salt Lake City International Airport", city: "Salt Lake City", country: "USA" },
  { iata: "PHL", name: "Philadelphia International Airport", city: "Philadelphia", country: "USA" },
  { iata: "CLT", name: "Charlotte Douglas International Airport", city: "Charlotte", country: "USA" },
  { iata: "BWI", name: "Baltimore/Washington International Airport", city: "Baltimore", country: "USA" },
  { iata: "STL", name: "St. Louis Lambert International Airport", city: "St. Louis", country: "USA" },
  { iata: "HNL", name: "Honolulu International Airport", city: "Honolulu", country: "USA" },
  { iata: "ANC", name: "Ted Stevens Anchorage International Airport", city: "Anchorage", country: "USA" },
  { iata: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada" },
  { iata: "YVR", name: "Vancouver International Airport", city: "Vancouver", country: "Canada" },
  { iata: "YUL", name: "Montréal-Trudeau International Airport", city: "Montreal", country: "Canada" },
  { iata: "YYC", name: "Calgary International Airport", city: "Calgary", country: "Canada" },
  { iata: "YEG", name: "Edmonton International Airport", city: "Edmonton", country: "Canada" },
  { iata: "YOW", name: "Ottawa Macdonald-Cartier International Airport", city: "Ottawa", country: "Canada" },
  { iata: "MEX", name: "Benito Juárez International Airport", city: "Mexico City", country: "Mexico" },
  { iata: "CUN", name: "Cancún International Airport", city: "Cancún", country: "Mexico" },

  // ── South America ──
  { iata: "GRU", name: "São Paulo Guarulhos International Airport", city: "São Paulo", country: "Brazil" },
  { iata: "GIG", name: "Rio de Janeiro–Galeão International Airport", city: "Rio de Janeiro", country: "Brazil" },
  { iata: "EZE", name: "Ministro Pistarini International Airport", city: "Buenos Aires", country: "Argentina" },
  { iata: "SCL", name: "Arturo Merino Benítez International Airport", city: "Santiago", country: "Chile" },
  { iata: "BOG", name: "El Dorado International Airport", city: "Bogotá", country: "Colombia" },
  { iata: "LIM", name: "Jorge Chávez International Airport", city: "Lima", country: "Peru" },

  // ── Australia & Pacific ──
  { iata: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia" },
  { iata: "MEL", name: "Melbourne Airport", city: "Melbourne", country: "Australia" },
  { iata: "BNE", name: "Brisbane Airport", city: "Brisbane", country: "Australia" },
  { iata: "PER", name: "Perth Airport", city: "Perth", country: "Australia" },
  { iata: "ADL", name: "Adelaide Airport", city: "Adelaide", country: "Australia" },
  { iata: "OOL", name: "Gold Coast Airport", city: "Gold Coast", country: "Australia" },
  { iata: "CNS", name: "Cairns Airport", city: "Cairns", country: "Australia" },
  { iata: "AKL", name: "Auckland Airport", city: "Auckland", country: "New Zealand" },
  { iata: "CHC", name: "Christchurch International Airport", city: "Christchurch", country: "New Zealand" },
  { iata: "WLG", name: "Wellington International Airport", city: "Wellington", country: "New Zealand" },
  { iata: "NAN", name: "Nadi International Airport", city: "Nadi", country: "Fiji" },
];
